language: php

php:
 - 7.1
 - 7.2
 - master

matrix:
  allow_failures:
    - php: master

before_script:
 - composer self-update
 - composer install

script:
 - composer validate
 - vendor/bin/parallel-lint src/ tests/
 - vendor/bin/phpunit
 - vendor/bin/phpstan analyze src tests --level=7
 - vendor/bin/php-cs-fixer fix --rules=@PSR2 -v --dry-run --stop-on-violation --using-cache=no .

