language: php

php:
 - 7.1
 - 7.2
 - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_script:
 - if php -v | grep -q 'Xdebug'; then phpenv config-rm xdebug.ini; fi
 - composer install

script:
 - composer run-script test

