language: php

php:
 - 7.0
 - 7.1
 - 7.2
 - master

before_script:
 - composer self-update
 - composer install

script:
 - composer validate
 - vendor/bin/parallel-lint src/ tests/
 - vendor/bin/phpunit

