language: php

php:
 - 7.1
 - 7.2
 - master

matrix:
  allow_failures:
    - php: master

before_script:
 - if php -v | grep -q 'Xdebug'; then phpenv config-rm xdebug.ini; fi
 - composer install

script:
 - composer run-script test

